//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMCMSSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoPanel
    {
        public string IPRowid { get; set; }
        public string IPHospRowid { get; set; }
        public string IPName { get; set; }
        public Nullable<System.DateTime> IPLoginDate { get; set; }
        public Nullable<int> IPDisplaySeq { get; set; }
        public string IPSectionName { get; set; }
        public string IPDoctorName { get; set; }
        public string IPNurseName { get; set; }
        public Nullable<int> IPCallNumber { get; set; }
        public bool IPOnLine { get; set; }
        public Nullable<int> IPLoginSeq { get; set; }
        public Nullable<int> IPCenterSeq { get; set; }
        public string IPCBDCode { get; set; }
        public string IPKey { get; set; }
        public string IPCipher { get; set; }
    }
}
