//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMCMSSys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysEntities : DbContext
    {
        public SysEntities()
            : base("name=SysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComboDetail> ComboDetail { get; set; }
        public virtual DbSet<ComboHDetail> ComboHDetail { get; set; }
        public virtual DbSet<ComboHMaster> ComboHMaster { get; set; }
        public virtual DbSet<ComboMaster> ComboMaster { get; set; }
        public virtual DbSet<SysHCDept> SysHCDept { get; set; }
        public virtual DbSet<SysHospitalClinic> SysHospitalClinic { get; set; }
        public virtual DbSet<SysHospitalClinicDoctor> SysHospitalClinicDoctor { get; set; }
        public virtual DbSet<SysHospitalClinicRoom> SysHospitalClinicRoom { get; set; }
        public virtual DbSet<SysHospitalDept> SysHospitalDept { get; set; }
        public virtual DbSet<SysMedicalGroup> SysMedicalGroup { get; set; }
        public virtual DbSet<SysMedicalGroupHospital> SysMedicalGroupHospital { get; set; }
        public virtual DbSet<SysOpinionReaction> SysOpinionReaction { get; set; }
        public virtual DbSet<SysOpinionReactionEmp> SysOpinionReactionEmp { get; set; }
        public virtual DbSet<SysProgram> SysProgram { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<SysRoleProgram> SysRoleProgram { get; set; }
        public virtual DbSet<SysUserRole> SysUserRole { get; set; }
        public virtual DbSet<UserData> UserData { get; set; }
        public virtual DbSet<UserMedicalGroup> UserMedicalGroup { get; set; }
        public virtual DbSet<SysHospital> SysHospital { get; set; }
        public virtual DbSet<SysHospitalGrafting> SysHospitalGrafting { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
