//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMCMSSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public string UserRowid { get; set; }
        public string UserCardNo { get; set; }
        public string UserCardNoExtend { get; set; }
        public string UserNo { get; set; }
        public string UserName { get; set; }
        public string UserIdno { get; set; }
        public Nullable<System.DateTime> UserBirthday { get; set; }
        public string UserGender { get; set; }
        public string UserBloodType { get; set; }
        public string UserMarriage { get; set; }
        public string UserAreaCode { get; set; }
        public string UserAddress { get; set; }
        public string UserMobilePhone { get; set; }
        public string UserHomePhone { get; set; }
        public string UserDept { get; set; }
        public string UserBelongDept { get; set; }
        public string UserRank { get; set; }
        public string UserJobCategory { get; set; }
        public string UserProIdentity { get; set; }
        public string UserPosition { get; set; }
        public Nullable<System.DateTime> UserOnBoardDay { get; set; }
        public Nullable<System.DateTime> UserResignationDay { get; set; }
        public string UserInstitute { get; set; }
        public string UserEducationDept { get; set; }
        public string UserEducationDegrees { get; set; }
        public string UserInsurance { get; set; }
        public string UserBankAccount { get; set; }
        public string UserWorkPlace { get; set; }
        public string UserBelongCompany { get; set; }
        public string UserPhoto { get; set; }
        public string UserLicense { get; set; }
        public string UserCertificate { get; set; }
        public Nullable<System.DateTime> UserBusinessDate { get; set; }
        public Nullable<System.DateTime> UserBusinessEndDate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> UserCreateDate { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> UserUpdateDate { get; set; }
        public string UserExperience { get; set; }
        public string UserExpertise { get; set; }
        public string UserTreatment { get; set; }
    }
}
